### ISSUE TITLE
add info on eventLabel associated with each eventAction in the analytics

### ISSUE THREAD

**Issue by oabuamsha** [wavesoft/virtual-atom-smasher#23]
Hi Ioannis,
I didn't find this explanation and I guess it is needed to document the analytics properly for the long-term.

I have this event: eventAction=ui_screen:change:screen.tuning eventLabel=1434469349324
I need to be sure of what this label means

**Comment by wavesoft** [comment]
Hello Oula, from the looks of it, it seems like a timestamp.
I haven't documented that, because this is one of the global properties available along with every event. I guess Jose chose to use that for some reason. It's not really related to the actual screen.chagne event.

**Comment by oabuamsha** [comment]
In fact it is a timestamp in milliseconds, I checked it, but there are other different event labels that represent percentage or duration I guess.
