### ISSUE TITLE
Unlocking new parameters

### ISSUE THREAD

**Issue by bsegal** [wavesoft/virtual-atom-smasher#4]
The navigation which allows one to open a new parameter isn't clear. I either get stuck on the "unlock" tab, or else I'm told I haven't enough science points. By the way, does one get science points for running simulations or only for passing tests?

**Comment by wavesoft** [comment]
Good points. 
I will add glow the ring around the machine parts that contain unlock-able elements.

Regarding your question, the player gets points both by passing tests (2 points for participating to the test and 8 points for mastering a topic), plus points upon a successful simulation run (2 points for running the simulation, 10 points for bringing the paper score below 4.0 and another 20 for bringing it below 1.0)

The latter two will be implemented soon.

**Comment by bsegal** [comment]
Many thanks for your replies!

Ben

**Comment by wavesoft** [comment]
This is going to be replaced with sequential levelling (check #13 )
