### ISSUE TITLE
The new Feedback forum

### ISSUE THREAD

**Issue by bsegal** [wavesoft/virtual-atom-smasher#5]
I tried out the new forum with the Feedback button. I sent you the following message, but I didn't ask for email answers, only via the forum messaging. No reply yet... 

**\* Here's my message:
I wanted to run a second job while the 1st was running. It warned me that it would overwrite the 1st job but when I went ahead in fact it just took some workers (3) from the 1st job and both went on running. Is this good? I think so.

PS: It's still not updating my papers...  Huh (smiley)
**\* End of message.....

**Comment by wavesoft** [comment]
This is changed on the current version. Now by default you are getting e-mail notifications.
